Greatest_common_divisor: Greatest_common_divisor.o
	g++ Greatest_common_divisor.o -o Greatest_common_divisor
Greatest_common_divisor.o: Greatest_common_divisor.cc
	g++ -c Greatest_common_divisor.cc
clean: 
	rm *.o Greatest_common_divisor

